//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAPOnlineKredit.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanzielleSituation
    {
        public int ID { get; set; }
        public Nullable<decimal> MonatsEinkommen { get; set; }
        public Nullable<decimal> Wohnkosten { get; set; }
        public Nullable<decimal> SonstigeEinkommen { get; set; }
        public Nullable<decimal> SonstigeAusgaben { get; set; }
        public Nullable<decimal> Raten { get; set; }
    
        public virtual Kunde Kunde { get; set; }
    }
}
