//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAPOnlineKredit.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakt
    {
        public int ID { get; set; }
        public Nullable<int> FKOrt { get; set; }
        public string Strasse { get; set; }
        public string eMail { get; set; }
        public string Telefonnummer { get; set; }
    
        public virtual Ort Ort { get; set; }
        public virtual Kunde Kunde { get; set; }
    }
}
