//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAPOnlineKredit.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde
    {
        public Kunde()
        {
            this.tblKredit = new HashSet<Kredit>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FKTitel { get; set; }
        public Nullable<int> FKFamilienstand { get; set; }
        public Nullable<int> FKWohnart { get; set; }
        public Nullable<int> FKAbschluss { get; set; }
        public Nullable<int> FKIdentifikationsart { get; set; }
        public string Staatsbuergerschaft { get; set; }
        public string Geschlecht { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public System.DateTime Geburtsdatum { get; set; }
        public Nullable<int> UnterhaltpflichtigeKinder { get; set; }
        public string Identifikationsnummer { get; set; }
    
        public virtual Abschluss tblAbschluss { get; set; }
        public virtual Arbeitgeber tblArbeitgeber { get; set; }
        public virtual Familienstand tblFamilienstand { get; set; }
        public virtual FinanzielleSituation tblFinanzielleSituation { get; set; }
        public virtual Identifikationsart tblIdentifikationsart { get; set; }
        public virtual Kontakt tblKontakt { get; set; }
        public virtual Konto tblKonto { get; set; }
        public virtual ICollection<Kredit> tblKredit { get; set; }
        public virtual Titel tblTitel { get; set; }
        public virtual Wohnart tblWohnart { get; set; }
        public virtual Land tblLand { get; set; }
        public virtual Login tblLogin { get; set; }
    }
}
